### ISSUE TITLE
Decide on how to allow layered builds

### ISSUE THREAD

**Issue by lcarva** [lcarva/osbs-box#43]
Currently it's not possible to use osbs-box's docker-registry, `172.17.0.1:5000`, to build layered images because it requires authentication, and `pull_base_image` plugin does not support authentication.

Once support is added to atomic-reactor's plugin, we can change, or at least document, that to build layered images set `source_registry_uri=172.17.0.1:5000` in `osbs.conf`.

Enabling this source registry by default would be problematic because it first needs to be populated with some initial images, rhel7 or fedora. But maybe this can be part of `osbs-box.py up` ?

Maybe pull-through registry can be used? https://docs.docker.com/registry/recipes/mirror/#use-case It seems unlikely.

**Comment by vrutkovs** [comment]
I think its safe to remove authentication from the registry at all:
```
    registry:
      image: registry:2
      ports:
        - 5000:5000
      environment:
        REGISTRY_HTTP_TLS_CERTIFICATE: /certs/domain.crt
        REGISTRY_HTTP_TLS_KEY: /certs/domain.key
      volumes_from:
        - shared-data
```
